export const cards = [
    {
      cardName: "Naruto Uzumaki",
      cardDescription: "O ninja que nunca desiste e sonha em se tornar Hokage.",
      cardAttr1: 80,
      cardAttr2: 50,
      cardAttr3: 65,
      cardImage: "https://a.storyblok.com/f/178900/960x540/ffef181a46/naruto.jpg/m/filters:quality(95)format(webp)",
      cardRare: "Very Rare",
      cardTrunfo: false,
    },
    {
      cardName: "Sasuke Uchiha",
      cardDescription: "Último sobrevivente do clã Uchiha, busca vingança.",
      cardAttr1: 50,
      cardAttr2: 70,
      cardAttr3: 55,
      cardImage: "https://imgix.ranker.com/list_img_v2/1377/2681377/original/best-sasuke-uchiha-quotes",
      cardRare: "Very Rare",
      cardTrunfo: false,
    },
    {
      cardName: "Sakura Haruno",
      cardDescription: "Ninja médica e membro do Time 7, possui força incrível.",
      cardAttr1: 60,
      cardAttr2: 55,
      cardAttr3: 80,
      cardImage: "https://upload.wikimedia.org/wikipedia/pt/0/03/Haruno_Sakura.jpg",
      cardRare: "Rare",
      cardTrunfo: false,
    },
    {
      cardName: "Kakashi Hatake",
      cardDescription: "Conhecido como o ninja copiador, mestre do Time 7.",
      cardAttr1: 50,
      cardAttr2: 85,
      cardAttr3: 70,
      cardImage: "https://pbs.twimg.com/media/E_VpBN5XEAcwQBx.jpg",
      cardRare: "Rare",
      cardTrunfo: false,
    },
    {
      cardName: "Gaara",
      cardDescription: "Jinchuuriki da Areia, protege sua vila com força imensa.",
      cardAttr1: 65,
      cardAttr2: 70,
      cardAttr3: 85,
      cardImage: "https://i.pinimg.com/564x/fb/b0/df/fbb0df1b85a9404734c73a236ee52794.jpg",
      cardRare: "Normal",
      cardTrunfo: false,
    },
    {
      cardName: "Shikamaru Nara",
      cardDescription: "Gênio estrategista, prefere evitar confrontos diretos.",
      cardAttr1: 50,
      cardAttr2: 65,
      cardAttr3: 50,
      cardImage: "https://narashikamaru.weebly.com/uploads/1/9/3/3/19332157/2658017_orig.jpg",
      cardRare: "Normal",
      cardTrunfo: false,
    },
    {
      cardName: "Rock Lee",
      cardDescription: "Especialista em taijutsu, possui determinação inabalável.",
      cardAttr1: 0,
      cardAttr2: 80,
      cardAttr3: 80,
      cardImage: "https://i.pinimg.com/736x/a7/f0/50/a7f050fea74ad5bfb9e830c4f7fa0b7d.jpg",
      cardRare: "Rare",
      cardTrunfo: false,
    },
    {
      cardName: "Hinata Hyuga",
      cardDescription: "Membro do clã Hyuga, possui habilidades únicas com o Byakugan.",
      cardAttr1: 65,
      cardAttr2: 60,
      cardAttr3: 75,
      cardImage: "https://images.uncyc.org/pt/thumb/9/90/Hinata_LSD.jpg/300px-Hinata_LSD.jpg",
      cardRare: "Normal",
      cardTrunfo: false,
    },
    {
      cardName: "Neji Hyuga",
      cardDescription: "Gênio do clã Hyuga, mestre em habilidades com o Byakugan.",
      cardAttr1: 70,
      cardAttr2: 65,
      cardAttr3: 70,
      cardImage: "https://pbs.twimg.com/media/ECrkykmWkAAKWb5.jpg",
      cardRare: "Rare",
      cardTrunfo: false,
    },
    {
      cardName: "Itachi Uchiha",
      cardDescription: "Misterioso e poderoso ninja, carrega um grande segredo.",
      cardAttr1: 80,
      cardAttr2: 90,
      cardAttr3: 90,
      cardImage: "https://www.magazine-hd.com/apps/wp/wp-content/uploads/2015/12/Itachi-Uchiha-itachi-uchiha-18374717-1280-720.jpg",
      cardRare: "Very Rare",
      cardTrunfo: false,
    },
  ];
  